### ISSUE TITLE
createToken shouldn't accept totpCertificate parameter

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#129]
The `createToken` mutation shouldn't accept the `totpCertificate` parameter as it cannot be a primary authentication method.

**Comment by ZaninAndrea** [comment]
At the moment `createToken` is an unauthenticated mutation, meaning that a malicious user could try to break only one of the factors and use that to create a permanent token, gaining access to the account and bypassing the protection of the second factor.

I would make `createToken` an authenticated mutation requiring only one primary or secondary authentication method, this way the security aspect is dealt with, because only the authenticated user can create tokens and at the same time we can allow the user to use the second factor to approve the operation.

**Comment by SamueleDassatti** [comment]
I agree, but I wouldn't allow users to use the TOTP when creating a token from Aurora.
