### ISSUE TITLE
Alternative APIs

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#219]
We should allow developers to fetch and mutate data on Igloo using standards and protocols other than GraphQL and HTTP, such as REST and MQTT. This would allow developers coming from existing IoT platforms to start prototyping Igloo-based devices using the standard and protocol they prefer.

**Comment by ZaninAndrea** [comment]
Bering is very tightly coupled with GraphQL and as such implementing a REST api would be very time-consuming, because most of the code would need from a partial to a complete rewrite. 

Transmitting GraphQL over other protocols on the other hand could probably be done with moderate effort, but it's has no support in the existing GraphQL ecosystem and the developers that use Igloo would need to code it themselves, because of this I would not recommend doing this.
