### ISSUE TITLE
Pending owner changes subscriptions

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#230]
Users do not receive a subscription when they receive, accept, or decline a pending owner change. Also, there is no subscription for when a pending owner change is either revoked or updated.

For this reason we should reintroduce the following subscriptions (this time only for receivers):
- pendingOwnerChangeDeclined
- pendingOwnerChangeAccepted
- pendingOwnerChangeCreated
- pendingOwnerChangeRevoked
- pendingOwnerChangeUpdated
- ownerChanged (to notify senders when they lose ownership of the environment)

**Comment by ZaninAndrea** [comment]
Consistently with the new naming the subscriptions will be:
- pendingTransferDeclined
- pendingTransferAccepted
- pendingTransferCreated
- pendingTransferRevoked

The subscriptions will be sent to both sender and receiver of the transfer and as such the ownerChanged subscription won't be needed (it is the same as the pendingTransferAccepted subscription)

@SamueleDassatti when would the `pendingTransferUpdated` subscription be triggered? There is no update mutation for pending transfers.

**Comment by SamueleDassatti** [comment]
The `pendingTransferUpdated` subscription should trigger when the receiver updates their name or email. It is currently possible to achieve this by using the `userUpdated(id:"")` subscription but I would prefer this approach as it is easier to implement client-side and more consistent.

Also, these subscriptions should not be sent to the sender as they already receive changes to `pendingTransfers` via the `environmentUpdated` subscription.

**Comment by ZaninAndrea** [comment]
I would send the subscriptions to the sender too for consistency and because `environmentUpdated` receives many messages, making it harder to listen for only one specific event, furthermore the redundancy is not an issue.

As for `pendingTransferUpdated` it would be the only case in which a subscription "updated" is triggered because a nested object is updated.

**Comment by SamueleDassatti** [comment]
> I would send the subscriptions to the sender too for consistency and because environmentUpdated receives many messages, making it harder to listen for only one specific event, furthermore the redundancy is not an issue.

Okay, I can see how this would be better for developers.

> As for pendingTransferUpdated it would be the only case in which a subscription "updated" is triggered because a nested object is updated.

Doesn't that happen with the `pendingShareUpdated` subscription?

**Comment by ZaninAndrea** [comment]
> Doesn't that happen with the `pendingShareUpdated` subscription?

That is triggered when the pendingShare `role` field is updated

**Comment by SamueleDassatti** [comment]
Okay, so I think we should update `pendingShareUpdated` so that it triggers when its `user` field changes and create `pendingTransferUpdated` and `shareUpdated` as they would allow developers to update their lists of pendingShares/pendingTransfers/shares with a single subscription, instead of forcing them to set up a subscription for each item of the list

**Comment by ZaninAndrea** [comment]
My point is that a similar issue is to be found with all of our subscriptions as none triggers if a nested field updates and as such it would be inconsistent to have this 2 behave differently.

Since this interaction can already be achieved (although with a slightly more complex setup) I don't think it's worth breaking the consistency; even more so considering that most developers would not know about this feature because it's not consistent with how the whole API works and can thus only be discovered through the docs.

**Comment by SamueleDassatti** [comment]
Okay, makes sense.

**Comment by ZaninAndrea** [comment]
closed by 580a5c67245296d452fee9742d2b010540dacc15
