### ISSUE TITLE
Simplify primary and secondary authentication factors

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#240]
We should rework the `primaryAuthenticationMethods` and `secondaryAuthenticationMethods` in order to make them simpler:
- replace the existing fields with an `authenticationMethods` field
- if the TOTP is enabled, it should be required along other authentication methods (provided that the user does not choose to log in with an email, e.g. if their device does not support WebAuthn)
- if the TOTP is the only method to be enabled, it should be the only factor required to log in
- users should be required to verify their email before enabling WebAuthn or disabling their password

**Comment by ZaninAndrea** [comment]
- although for the time being TOTP will remain the only secondary authentication method I would keep the distinction for future compatibility and because it makes clear which methods are alternatives, for example enabling password and webauthn as alternative primary and totp as secondary would lead to `authenticationMethods` being `[PASSWORD, WEBAUTHN, TOTP]` which does not clearly represent the relation between the 3
- Allowing TOTP as only factor is not possible as it is extremely weak.
- The users are created without any authentication method enabled apart from email, so at sign up password is disabled and email is not verified. We can require the email verification before enabling WebAuthn as only factor, I would say that the clearest thing from the user perspective is to require email verification before setting any authentication method, this to avoid having a different flow to enable password and webauthn

**Comment by SamueleDassatti** [comment]
I agree on keeping primary and secondary factors as distinct fields and not allowing totp to be the only required factor. As for the email verification issue, we should first decide whether to keep WebAuthn and email authentication based on whether the former can be offered only on devices on which a biometric authentication method has been registered.

**Comment by ZaninAndrea** [comment]
Todos Bering:
- [ ] add error when a user with an unverified email runs the mutation `setWebauthn`
- [ ] removed WEBAUTHN and PASSWORD as secondary authentication methods
- [ ] add WebAuthnKey type
- [ ] add bound/unbound and nickname fields to WebAuthnKeys
- [ ] add field WebAuthnKeys to user
- [ ] rename `setWebAuthn` to `createWebAuthnKey`
- [ ] implement `webAuthnKey` and `deleteWebAuthnKey` mutations
