### ISSUE TITLE
String value should not be settable to ""

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#265]
Throw an error if user tries to set a `stringValue` to "". The `allowedValues` field should also throw an error when one of its items is set to "" and should accept `null` as a valid value.

**Comment by ZaninAndrea** [comment]
Why would we do something like this?

**Comment by SamueleDassatti** [comment]
Since stringValues are now nullable, it would make sense to force developers to use either the empty string or null, as it would block them from setting allowedValues to ["", null], which would not make sense visualization wise.

**Comment by ZaninAndrea** [comment]
- `allowedValues` will not accept `null` as value, because that's inconsistent, but `null` is always accepted as `value` regardless of the `allowedValues`
- `allowedValues` will not accept an empty string as value to avoid visualization issues, the option to set to `null` is always permitted so there should always be an empty entry
- `value` will accept an empty string as value (if `allowedValues` is not set) as it would be very confusing for developers not being able to set a string to "" and it would force to parse `null` to empty string when handling those.
In Aurora (if `allowedValues` is not set) both null and empty string should be displayed as empty strings and the user can only set to an empty string, since `allowedValues` is not set the thing developer should anyways have build a method to manage any string or null value.
