### ISSUE TITLE
developerThings authorization bug

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#293]
The `user{developerThings}` query return "You are not allowed to perform this operation" despite being able to corrently fetch all developer things. The `thing(id:"")` query used on a `developerThing` returns "You are not allowed to perform this operation" but does not fetch the `thing`.

**Comment by ZaninAndrea** [comment]
Can you give more details on the precise query you are trying to make?

The producer has the authorization to fetch a thing, but not all its fields, so for example a query like this will return the "You are not allowed to perform this operation" error, because the name is a field that the producer is not allowed to fetch
```
{
  user{
    developerThings(limit:3){
      name
    }
  }
}
```

**Comment by SamueleDassatti** [comment]
The query included the name field. Closing the issue.
